import React from 'react';

export default function MemoryGraph() {
  return (
    <div className="page-container" style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      <header className="page-header">
        <h1 className="page-title">Memory Graph</h1>
        <p className="page-subtitle">Visualize your connected neural data.</p>
      </header>

      <div className="glass-card" style={{ flex: 1, minHeight: '500px', display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'hidden' }}>
        
        {/* Decorative Graph Network */}
        <div style={{ position: 'absolute', width: '100%', height: '100%', opacity: 0.5 }}>
          <svg width="100%" height="100%">
            <line x1="20%" y1="30%" x2="50%" y2="50%" stroke="var(--color-neon-cyan)" strokeWidth="1" />
            <line x1="50%" y1="50%" x2="80%" y2="40%" stroke="var(--color-neon-purple)" strokeWidth="1" />
            <line x1="50%" y1="50%" x2="60%" y2="80%" stroke="var(--color-neon-cyan)" strokeWidth="1" />
            <line x1="30%" y1="70%" x2="50%" y2="50%" stroke="var(--color-neon-purple)" strokeWidth="1" />
            
            <circle cx="20%" cy="30%" r="6" fill="var(--color-neon-cyan)" />
            <circle cx="80%" cy="40%" r="8" fill="var(--color-neon-purple)" />
            <circle cx="60%" cy="80%" r="5" fill="var(--color-neon-cyan)" />
            <circle cx="30%" cy="70%" r="7" fill="var(--color-neon-purple)" />
            
            {/* Center Node */}
            <circle cx="50%" cy="50%" r="12" fill="#fff" style={{ filter: 'drop-shadow(0 0 10px var(--color-neon-cyan))' }} />
          </svg>
        </div>

        <div style={{ position: 'relative', zIndex: 1, textAlign: 'center', background: 'var(--color-bg-card)', padding: '24px', borderRadius: '16px', backdropFilter: 'blur(8px)' }}>
          <h3 style={{ marginBottom: '8px' }}>Interactive Node View</h3>
          <p style={{ color: 'var(--color-text-secondary)', fontSize: '14px', maxWidth: '300px' }}>
            Explore entities, relationships, and context clusters generated by AXON.
          </p>
        </div>
      </div>
    </div>
  );
}
